# .github/workflows/build-test.yml

name: PlatformIO Build Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checks-out your repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. (FIX) Run your environment setup script
      - name: Run environment setup script
        run: |
          chmod +x setup_env.sh
          ./setup_env.sh

      # 3. Sets up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      # 4. Installs PlatformIO Core
      - name: Install PlatformIO
        run: pip install -U platformio

      # 5. Builds the project
      - name: Build PlatformIO Project
        run: pio run -e Gadadar4Ch
